name: marvel_characters_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  cached_network_image: ^3.3.0
  cupertino_icons: ^1.0.6
  dotenv: ^4.2.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_native_splash: ^2.3.6
  flutter_riverpod: ^2.4.4
  go_router: ^12.0.0
  http: ^1.1.0
  image: ^4.1.3
  pagination_view: ^2.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/marvel_icon.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#000000"
  image: "assets/icon/marvel_icon.png"

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/image/
    - assets/icon/
